# ~/.config/starship.toml

# 设置配置范例，开启编辑器的自动补全
"$schema" = 'https://starship.rs/config-schema.json'

# 在命令之间插入空行
add_newline = false

format = """[OS Name](bold bright-blue) $all"""

# 将提示符的“❯”替换为“$”
[character] # character 是我们正在配置的组件
success_symbol = "[\\$](bold blue)" # 设置 success_symbol 字段为绿色加粗的“$”
error_symbol = "[\\$](bold red)"

# 命令提示符不换行
[line_break]
disabled = true

# 电池电量显示配置
[battery]
full_symbol = "[on](bold white) Battery "
charging_symbol = "[in](bold white) Charging "
discharging_symbol = "[on](bold white) Battery "
unknown_symbol = "[on](bold white) Battery "
empty_symbol = "[on](bold white) Battery "
display = [
  { style = "red bold", threshold = 30 },
  { style = "yellow bold", threshold = 50 },
  { style = "green bold", threshold = 100 },
]

# 关闭命令执行时间显示
[cmd_duration]
disabled = true

# 针对不同语言的配置项，将 nerd fonts 或 emoji 图标更换为其名称描述
[dart]
symbol = "Dart "

[deno]
symbol = "Deno "

[git_branch]
symbol = "Branch "

[git_commit]
commit_hash_length = 6
tag_symbol = "Commit "

[git_status]
deleted = '-'

[golang]
symbol = "Go "

[haskell]
symbol = "Haskell "

[java]
symbol = "Java "

[kotlin]
symbol = "Kotlin "

[lua]
symbol = "Lua "

[nodejs]
symbol = "Node "

[package]
symbol = "Package Version "

[perl]
symbol = "Perl "

[php]
symbol = "PHP "

[ruby]
symbol = "Ruby "

[rust]
symbol = "Rust "
